CREATE TABLE TBL_PRODUTO (
  id_produto INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  dc_nome_produto INTEGER UNSIGNED NULL,
  PRIMARY KEY(id_produto)
);

CREATE TABLE TBL_TICKET (
  id_ticket INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  numero_ticket_premiado INTEGER UNSIGNED NULL,
  id_produto INTEGER UNSIGNED NULL,
  PRIMARY KEY(id_ticket)
  
);

